### ISSUE TITLE
Tests fail with bundler 1.12.5

### ISSUE THREAD

**Issue by lrasmus** [OSEHRA/popHealth#47]
Noticed in latest CI build that unit tests fail after bundler is updated to the latest version (1.12.5):

```
There was an error while trying to load the gem 'quality-measure-engine'. (Bundler::GemRequireError)
Gem Load Error is: undefined method `field' for QME::QualityReport:Class
Backtrace for gem load error is:
/home/travis/build/OSEHRA/popHealth/lib/qme/quality_report.rb:6:in `<class:QualityReport>'
/home/travis/build/OSEHRA/popHealth/lib/qme/quality_report.rb:4:in `<module:QME>'
/home/travis/build/OSEHRA/popHealth/lib/qme/quality_report.rb:3:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.1.2/gems/quality-measure-engine-3.1.2/lib/quality-measure-engine.rb:10:in `require'
/home/travis/.rvm/gems/ruby-2.1.2/gems/quality-measure-engine-3.1.2/lib/quality-measure-engine.rb:10:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.1.2/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
/home/travis/.rvm/gems/ruby-2.1.2/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
/home/travis/.rvm/gems/ruby-2.1.2/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
/home/travis/.rvm/gems/ruby-2.1.2/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
/home/travis/.rvm/gems/ruby-2.1.2/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
/home/travis/.rvm/gems/ruby-2.1.2/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
/home/travis/.rvm/gems/ruby-2.1.2/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
/home/travis/build/OSEHRA/popHealth/config/application.rb:15:in `<top (required)>'
/home/travis/build/OSEHRA/popHealth/config/environment.rb:2:in `require'
/home/travis/build/OSEHRA/popHealth/config/environment.rb:2:in `<top (required)>'
/home/travis/build/OSEHRA/popHealth/test/test_helper.rb:4:in `require'
/home/travis/build/OSEHRA/popHealth/test/test_helper.rb:4:in `<top (required)>'
/home/travis/build/OSEHRA/popHealth/test/functional/admin_controller_test.rb:1:in `require'
/home/travis/build/OSEHRA/popHealth/test/functional/admin_controller_test.rb:1:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:15:in `require'
/home/travis/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:15:in `block in <main>'
/home/travis/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4:in `select'
/home/travis/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4:in `<main>'
```

**Comment by lrasmus** [comment]
Looking into this

**Comment by lrasmus** [comment]
Have tested previous versions - able to reproduce the error on bundler 1.12.0, but not 1.11.2
